FROM eclipse-temurin:17-jre

WORKDIR /app

COPY ./build/libs/withDog-user-analytics-0.0.1-SNAPSHOT.jar withDog-user-analytics-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar","withDog-user-analytics-0.0.1-SNAPSHOT.jar"]