FROM openjdk:17-jre

WORKDIR /app

COPY ./build/libs/withdog-user-analytics-0.0.1-SNAPSHOT.jar withdog-user-analytics-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar","withdog-user-analytics-0.0.1-SNAPSHOT.jar"]