spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true


#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    withdog.event.consumer: DEBUG
#logging:
#  level:
#    org.apache.kafka: DEBUG
#    org.springframework.kafka: DEBUG