services:

  withdog-api:
    image: hyunsense/withdog-api:latest
    restart: always
    networks:
      - withdog-net
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8080"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - withdog-net
    volumes:
      # Nginx 설정 파일 마운트
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Let's Encrypt 설정/인증서 폴더 공유
      - ./data/certbot/conf:/etc/letsencrypt
      # Let's Encrypt challenge 파일 폴더 공유
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - withdog-api

  certbot:
    image: certbot/certbot
    volumes:
      # Let's Encrypt 설정/인증서 폴더 공유 (인증서 저장 폴더)
      - ./data/certbot/conf:/etc/letsencrypt
      # Let's Encrypt challenge 파일 폴더 공유 (인증용 파일 저장 폴더)
      - ./data/certbot/www:/var/www/certbot
    networks:
      - withdog-net
    depends_on:
      - nginx

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - withdog-redis-data:/data
    networks:
      - withdog-net


networks:
  withdog-net:
    driver: bridge

volumes:
  withdog-redis-data:
