services:

  api-server:
    image: withdog-api-server:latest
#    image: hyunsense1022@gmail.com/withdog-api-server:latest
    ports:
      - "8080:8080"
    networks:
      - withdog-net
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9093,kafka3:9094
    depends_on:
      - redis
      - kafka1
      - kafka2
      - kafka3

  user-analytics:
    image: withdog-user-analytics:latest
#    image: hyunsense1022@gmail.com/withdog-user-analytics:latest
    networks:
      - withdog-net
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9093,kafka3:9094
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - kafka1
      - kafka2
      - kafka3

  redis-ui:
    image: redis/redisinsight:latest
    ports:
      - "5000:5540"
    networks:
      - withdog-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8888:8080"
    networks:
      - withdog-net
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9093,kafka3:9094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183

  #Redis admin, password 필요할듯
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - withdog-net
    volumes:
      - redis-data:/data

#    zoonavigator:
#      image: elkozmon/zoonavigator:latest
#      ports:
#        - "9000:9000"
#      networks:
#        - withdog-net
#      depends_on:
#        - zookeeper1
#        - zookeeper2
#        - zookeeper3
#      environment:
#        - HTTP_PORT=9000
#        - ZK_DEFAULT_NODE=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183

  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
    ports:
      - "2181:2181"
    networks:
      - withdog-net
    volumes:
      - zookeeper1-data:/var/lib/zookeeper

  zookeeper2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
    ports:
      - "2182:2182"
    networks:
      - withdog-net
    volumes:
      - zookeeper2-data:/var/lib/zookeeper

  zookeeper3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2889:3889;zookeeper3:2890:3890
    ports:
      - "2183:2183"
    networks:
      - withdog-net
    volumes:
      - zookeeper3-data:/var/lib/zookeeper

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 4
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - withdog-net
    volumes:
      - kafka1-data:/var/lib/kafka

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 4
    ports:
      - "9093:9093"
      - "29093:29093"
    networks:
      - withdog-net
    volumes:
      - kafka2-data:/var/lib/kafka

  kafka3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,PLAINTEXT_HOST://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 4
    ports:
      - "9094:9094"
      - "29094:29094"
    networks:
      - withdog-net
    volumes:
      - kafka3-data:/var/lib/kafka

networks:
  withdog-net:
    driver: bridge

volumes:
  redis-data:
  zookeeper1-data:
  zookeeper2-data:
  zookeeper3-data:
  kafka1-data:
  kafka2-data:
  kafka3-data: