spring:
  servlet:
    multipart:
      max-file-size: 2MB # 개별(단일)파일 크기 제한
      max-request-size: 5MB # HTTP(Multipart/form-data) 요청 크기 제한

  web:
    resources:
      # 정적 리소스 매핑 끄기
      add-mappings: false
  profiles:
    include: aws, jwt, db
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug
        type:
          descriptor:
            sql: trace
server:
  address: 0.0.0.0 #외부접속허용
  port: 8080
  tomcat:
    connection-timeout: 15000