name: CI/CD withdog BackEnd workflow

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Create application-aws.yml
        run: |
          cd ./backend/src/main/resources
          touch application-aws.yml
          echo "${{secrets.APPLICATION_AWS_YML}}" > application-aws.yml
          cat application-aws.yml

      - name: Create application-jwt.yml
        run: |
          cd ./backend/src/main/resources
          touch application-jwt.yml
          echo "${{secrets.APPLICATION_JWT_YML}}" > application-jwt.yml
          cat application-jwt.yml

      - name: Create application-db.yml
        run: |
          cd ./backend/src/main/resources
          touch application-db.yml
          echo "${{secrets.APPLICATION_DB_YML}}" > application-db.yml
          cat application-db.yml

      - name: Grant execute permission to gradlew
        run: chmod +x ./backend/gradlew

      - name: Build with gradle
        run: |
          cd ./backend
          ./gradlew clean build -x test

      - name: List files in build/libs
        run: ls ./backend/build/libs

      - name: Create ZIP package with all files
        run: |
          mkdir deploy-package
          cp ./backend/build/libs/withDog-0.0.1-SNAPSHOT.jar deploy-package/
          cp -r ./backend/scripts deploy-package/
          cp ./backend/appspec.yml deploy-package/ 

          zip -r ./deploy-package.zip deploy-package/

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZIP artifact
          path: ./deploy-package.zip

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: ZIP artifact

      - name: List files in Current Directory
        run: ls ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3 (ZIP package)
        run: |
           aws s3 cp deploy-package.zip s3://withdog-deploy/

      - name: Start CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name withdog \
            --deployment-group-name withdog-deploy-group \
            --s3-location bucket=withdog-deploy,bundleType=zip,key=deploy-package.zip \
            --region ap-northeast-2
