name: CI/CD withdog BackEnd workflow

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 멀티-플랫폼 빌드를 위한 QEMU 설정
      # - name: Set up QEMU
        # uses: docker/setup-qemu-action@v3

      # Docker Buildx 설정 (고급 빌드 기능 활성화)
      # - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/withdog-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Start CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name withdog \
            --deployment-group-name withdog-deploy-group \
            --region ap-northeast-2 \
            --description "Deploying from Github Actions ${{ github.sha }}" \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
